version: '3'
services:
  app:
    container_name: python-app
    build: .
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./
      dockerfile: mysql.docker
    ports:
      - '3306:3306'
